services:
 db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password not set}
   volumes:
     - postgres-data:/var/lib/postgresql/data
   ports:
     - 5432:5432
# adminer:
#   image: adminer
#   restart: always
#   ports:
#     - 8080:8080
 ui:
   build:
     context: ./ui
     dockerfile: Dockerfile
   ports:
     - 5000:80
   depends_on:
     - db
volumes:
 postgres-data: