apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-api-deployment-replicas
  labels:
    app: my-k8s-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nixeramus/api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
